dict_associations = {
    "Premier League": {
        "name": ["EPL"],
        "teams": {
            "Manchester City": ["Man City"],
            "Liverpool": ["Liverpool"],
            "Chelsea": ["Chelsea"],
            "Tottenham": ["Tottenham"],
            "Arsenal": ["Arsenal"],
            "Manchester United": ["Manchester Utd", "Man Utd"],
            "Wolverhampton": ["Wolverhampton Wanderers", "Wolves"],
            "Everton": ["Everton"],
            "Leicester City": ["Leicester"],
            "West Ham United": ["West Ham Utd", "West Ham"],
            "Watford": ["Watford"],
            "Crystal Palace": ["Crystal Palace"],
            "Newcastle United": ["Newcastle Utd", "Newcastle"],
            "Bournemouth": ["Bournemouth"],
            "Burnley": ["Burnley"],
            "Southampton": ["Southampton"],
            "Brighton": ["Brighton", "Brighton & Hove Albion"],
            "Norwich City": ["Norwich"],
            "Sheffield United": ["Sheffield Utd"],
            "Aston Villa": ["Aston Villa"],
            "Fulham": ["Fulham"],
            "Cardiff City": ["Cardiff"],
            "Huddersfield": ["Huddersfield", "Huddersfield Town"],
            "Stoke City": ["Stoke"],
            "Swansea City": ["Swansea"],
            "Hull City": ["Hull"],
            "Middlesbrough": ["Middlesbrough"],
            "Sunderland": ["Sunderland"],
            "West Brom": ["West Bromwich Albion"],
            "QP Rangers": ["QPR", "Queens Park Rangers"]}},
    "Bundesliga": {
        "name": ["Bundesliga"],
        "teams": {
            "Bayern Munich": ["Bayern M.", "Bayern München"],
            "Dortmund": ["Borussia Dortmund"],
            "RB Leipzig": ["RasenBallsport Leipzig"],
            "Leverkusen": ["Bayer Leverkusen", "Bayer 04 Leverkusen"],
            "Monchengladbach": ["M'gladbach", "Borussia M.Gladbach", "B. Monchengladbach", "Borussia M'gladbach"],
            "Wolfsburg": ["Wolfsburg"],
            "Freiburg": ["Freiburg"],
            "Schalke 04": ["Schalke", "FC Schalke 04"],
            "Hoffenheim": ["Hoffenheim", "1899 Hoffenheim"],
            "FC Koln": ["Köln", "FC Cologne", "1. FC Köln"],
            "Hertha Berlin": ["Hertha", "Hertha BSC"],
            "Augsburg": ["FC Augsburg", "Augsburg"],
            "Union Berlin": ["Union Berlin", "1. FC Union Berlin"],
            "Eintracht Frankfurt": ["E. Frankfurt"],
            "FSV Mainz": ["Mainz 05", "Mainz", "1. FSV Mainz 05"],
            "Dusseldorf": ["Fortuna", "Fortuna Duesseldorf", "Düsseldorf", "Fortuna Düsseldorf"],
            "Werder Bremen": ["Bremen"],
            "Paderborn": ["Paderborn", "SC Paderborn 07"],
            "FC Nurnberg": ["Nürnberg", "Nuernberg", "1. FC Nürnberg"],
            "Hannover 96": ["Hannover"],
            "Stuttgart": ["VfB Stuttgart"],
            "Hamburger SV": ["HSV"],
            "Darmstadt": ["Darmstadt", "Darmstadt 98"],
            "Ingolstadt": ["Ingolstadt"]}},
    "La Liga": {
        "name": ["LaLiga", "La liga", "La_liga"],
        "teams": {
            "Alaves": ["Alavés", "Deportivo Alavés"],
            "Athletic Bilbao": ["Athletic", "Athletic Club", "Ath Bilbao"],
            "Atletico Madrid": ["Atl. Madrid", "Atlético Madrid"],
            "Celta Vigo": ["Celta"],
            "Eibar": ["Eibar"],
            "Espanyol": ["Espanyol"],
            "Barcelona": ["FC Barcelona"],
            "Sevilla": ["FC Sevilla"],
            "Getafe": ["Getafe"],
            "Granada": ["Granada CF"],
            "Leganes": ["Leganés"],
            "Levante": ["Levante"],
            "Mallorca": ["Mallorca", "RCD Mallorca"],
            "Osasuna": ["Osasuna"],
            "Real Betis": ["Betis"],
            "Real Madrid": ["Real Madrid"],
            "Real Sociedad": ["Real Sociedad"],
            "Valencia": ["Valencia"],
            "Valladolid": ["Real Valladolid"],
            "Villarreal": ["Villarreal"],
            "Girona": ["Girona"],
            "Huesca": ["SD Huesca"],
            "Rayo Vallecano": ["Rayo Vallecano"],
            "Deportivo": ["Deportivo La Coruna", "Dep. La Coruna", "Deportivo La Coruña"],
            "Las Palmas": ["Las Palmas"],
            "Malaga": ["Málaga"],
            "Sporting Gijon": ["Sporting", "Sporting Gijón"],
            "Almeria": ["Almería"],
            "Cordoba": ["Córdoba"],
            "Elche": ["Elche", "Elche CF"]}},
    "Serie A": {
        "name": ["Italy - Serie A", "Serie_A"],
        "teams": {
            "AC Milan": ["Milan"],
            "AS Roma": ["Roma"],
            "Atalanta": ["Atalanta"],
            "Bologna": ["Bologna"],
            "Brescia": ["Brescia"],
            "Cagliari": ["Cagliari"],
            "Fiorentina": ["Fiorentina"],
            "Genoa": ["Genoa"],
            "Verona": ["Hellas Verona"],
            "Inter": ["Inter Milan"],
            "Juventus": ["Juventus"],
            "Lazio": ["Lazio"],
            "Lecce": ["Lecce"],
            "Napoli": ["Napoli"],
            "Parma": ["Parma Calcio 1913"],
            "Palermo": ["Palermo"],
            "Cesena": ["Cesena"],
            "Sampdoria": ["Sampdoria"],
            "Sassuolo": ["Sassuolo"],
            "SPAL": ["SPAL 2013"],
            "Torino": ["Torino"],
            "Udinese": ["Udinese"],
            "Chievo": ["Chievo", "ChievoVerona"],
            "Empoli": ["Empoli"],
            "Frosinone": ["Frosinone"],
            "Benevento": ["Benevento"],
            "Crotone": ["Crotone"],
            "Pescara": ["Pescara"],
            "Carpi": ["Carpi"]}},
    "RFPL": {
        "name": ["Russia - Premier League", "Premier Liga", "Premier League"],
        "teams": {
            "Akhmat Grozny": ["Akhmat", "FK Akhmat", "Terek Grozny"],
            "Arsenal Tula": ["Arsenal"],
            "CSKA Moscow": ["CSKA"],
            "Dinamo Moscow": ["Dynamo", "Dynamo Moscow"],
            "FC Krasnodar": ["Krasnodar"],
            "FC Tambov": ["Tambov"],
            "Krylya Sovetov": ["Krylya Sovetov Samara", "FK Krylya Sovetov Samara"],
            "Lokomotiv Moscow": ["Lokomotiv", "Lokomotiv M."],
            "Orenburg": ["FC Orenburg"],
            "Sochi": ["PFC Sochi", "FC Sochi"],
            "Rostov": ["FC Rostov"],
            "Rubin Kazan": ["Rubin Kazan"],
            "Spartak Moscow": ["Spartak"],
            "Ufa": ["FC Ufa"],
            "Ural": ["Ural", "Ural Yekaterinburg"],
            "Zenit": ["Zenit St. Petersburg"],
            "Anzhi": ["Anzhi Makhachkala", "FK Anzi Makhackala"],
            "Yenisey": ["FC Yenisey Krasnoyarsk", "Yenisey Krasnoyarsk"],
            "Amkar Perm": ["Amkar"],
            "SKA Khabarovsk": ["SKA", "SKA-Khabarovsk"],
            "Tosno": ["Tosno", "FK Tosno"],
            "Tomsk": ["Tom Tomsk"],
            "Kuban": ["Kuban Krasnodar"],
            "Saransk": ["Mordovia", "Mordovya", "Mordovia Saransk"],
            "Torpedo Moscow": ["Torpedo"]}},
    "Ligue 1": {
        "name": ["France - Ligue 1", "Ligue_1"],
        "teams": {
            "Amiens": ["Amiens"],
            "Angers": ["Angers"],
            "Bordeaux": ["Bordeaux"],
            "Brest": ["Brest", "Stade Brestois 29"],
            "Dijon": ["Dijon"],
            "Lille": ["Lille", "Lille OSC"],
            "Lyon": ["Lyon", "Olympique Lyonnais"],
            "Marseille": ["Marseille", "Olympique de Marseille"],
            "Metz": ["Metz"],
            "Monaco": ["AS Monaco"],
            "Montpellier": ["Montpellier"],
            "Nantes": ["Nantes", "FC Nantes"],
            "Nice": ["Nice", "OGC Nice"],
            "Nimes": ["Nîmes", "Nîmes Olympique"],
            "Paris SG": ["PSG", "Paris Saint Germain", "Paris Saint-Germain"],
            "Reims": ["Reims", "Stade de Reims"],
            "Rennes": ["Rennes", "Stade Rennais"],
            "Saint-Etienne": ["Saint-Étienne", "St Etienne"],
            "Strasbourg": ["Strasbourg"],
            "Toulouse": ["Toulouse"],
            "Caen": ["Caen"],
            "Guingamp": ["Guingamp"],
            "Troyes": ["Troyes"],
            "Bastia": ["SC Bastia"],
            "Lorient": ["Lorient"],
            "Nancy": ["Nancy"],
            "GFC Ajaccio": ["GFC Ajaccio"],
            "Evian TG": ["Evian", "Evian Thonon Gaillard"],
            "Lens": ["Lens", "RC Lens"]}}
}
