from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 769)
        app_icon = QtGui.QIcon()
        app_icon.addFile('icons/ball-16.png', QtCore.QSize(16, 16))
        app_icon.addFile('icons/ball-24.png', QtCore.QSize(24, 24))
        app_icon.addFile('icons/ball-32.png', QtCore.QSize(32, 32))
        MainWindow.setWindowIcon(app_icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pixmap = QtGui.QPixmap("icons/logo.png")
        self.lbl = QtWidgets.QLabel(self.centralwidget)
        self.lbl.setPixmap(self.pixmap)
        self.lbl.setGeometry(QtCore.QRect(220, 0, 600, 60))

        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 480, 781, 111))
        self.tableWidget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(24)
        self.tableWidget_3.setColumnWidth(0, 100)
        self.tableWidget_3.setColumnWidth(1, 20)
        self.tableWidget_3.setColumnWidth(2, 20)
        self.tableWidget_3.setColumnWidth(3, 20)
        self.tableWidget_3.setColumnWidth(4, 20)
        self.tableWidget_3.setColumnWidth(5, 20)
        self.tableWidget_3.setColumnWidth(6, 20)
        self.tableWidget_3.setColumnWidth(7, 20)
        self.tableWidget_3.setColumnWidth(8, 20)
        self.tableWidget_3.setColumnWidth(9, 20)
        self.tableWidget_3.setColumnWidth(10, 20)
        self.tableWidget_3.setColumnWidth(11, 20)
        self.tableWidget_3.setColumnWidth(12, 20)
        self.tableWidget_3.setColumnWidth(13, 20)
        self.tableWidget_3.setColumnWidth(14, 20)
        self.tableWidget_3.setColumnWidth(15, 20)
        self.tableWidget_3.setColumnWidth(16, 20)
        self.tableWidget_3.setColumnWidth(17, 50)
        self.tableWidget_3.setColumnWidth(18, 50)
        self.tableWidget_3.setColumnWidth(19, 50)
        self.tableWidget_3.setColumnWidth(20, 50)
        self.tableWidget_3.setColumnWidth(21, 20)
        self.tableWidget_3.setColumnWidth(22, 20)
        self.tableWidget_3.setColumnWidth(23, 20)
        self.tableWidget_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Название команд")
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Количество матчей")
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Побед")
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ничей")
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Поражений")
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Забитых голов")
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Пропущенных голов")
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Разница в голах")
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Очки")
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Последние 6 результатов")
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Очки за игру")
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Очки за игру в последних 8 матчах")
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Матчи без пропущенных голов")
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Матчи без забитых голов")
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых забитых голов")
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов без штрафных и собственных")
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых забитых голов")
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых забитых голов без штрафных и собственных")
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Разница между забитыми и пропущенными без штрафных и собственных")
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Разрешенные пасы за оборонительные действия в оппозиционной половине")
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Разрешенные пасы противников за оборонительные действия в оппозиционной половине")
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Завершенные пасы в пределах примерно 20 ярдов от гола")
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Завершенные пасы противников в пределах примерно 20 ярдов от гола")
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемое количество очков")
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 781, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.team_1 = QtWidgets.QWidget()
        self.team_1.setObjectName("team_1")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.team_1)
        self.tableWidget_1.setGeometry(QtCore.QRect(0, 0, 771, 381))
        self.tableWidget_1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_1.setFont(font)
        self.tableWidget_1.setStyleSheet("")
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(23)
        self.tableWidget_1.setColumnWidth(0, 100)
        self.tableWidget_1.setColumnWidth(1, 60)
        self.tableWidget_1.setColumnWidth(2, 80)
        self.tableWidget_1.setColumnWidth(3, 60)
        self.tableWidget_1.setColumnWidth(4, 50)
        self.tableWidget_1.setColumnWidth(5, 40)
        self.tableWidget_1.setColumnWidth(6, 20)
        self.tableWidget_1.setColumnWidth(7, 20)
        self.tableWidget_1.setColumnWidth(8, 20)
        self.tableWidget_1.setColumnWidth(9, 20)
        self.tableWidget_1.setColumnWidth(10, 20)
        self.tableWidget_1.setColumnWidth(11, 20)
        self.tableWidget_1.setColumnWidth(12, 60)
        self.tableWidget_1.setColumnWidth(13, 70)
        self.tableWidget_1.setColumnWidth(14, 50)
        self.tableWidget_1.setColumnWidth(15, 60)
        self.tableWidget_1.setColumnWidth(16, 20)
        self.tableWidget_1.setColumnWidth(17, 70)
        self.tableWidget_1.setColumnWidth(18, 80)
        self.tableWidget_1.setColumnWidth(19, 80)
        self.tableWidget_1.setColumnWidth(20, 80)
        self.tableWidget_1.setColumnWidth(21, 50)
        self.tableWidget_1.setColumnWidth(22, 20)
        self.tableWidget_1.setRowCount(11)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(0, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(1, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(2, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(3, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(4, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(5, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(6, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(7, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(8, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(9, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_1.setCellWidget(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Имя и фамилия игрока")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Позиция")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Количество сыгранных игр")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Время проведенное в играх")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Количество голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Голов без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Пасы приведенные к голу")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Shorts за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Пасы приведенные к short за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сумма ожидаемых голов от удара с решающей передачей игроку")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Общее ожидание голов каждого паса, в котором участвует игрок")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Общее ожидание голов каждого паса, в котором участвует игрок без решаюшей передачи и ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов за 90 минут без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Оиждаемых пасов за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов и пасы за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов и пасы за 90 минут без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов каждого паса, в котором участвует игрок за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip(
            "Ожидаемых голов каждого паса, в котором участвует игрок за 90 минут без ключевых передач и ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Желтых карт")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Красных карт")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_1.setHorizontalHeaderItem(22, item)
        self.tabWidget.addTab(self.team_1, "")
        self.team_2 = QtWidgets.QWidget()
        self.team_2.setObjectName("team_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.team_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 771, 381))
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(23)
        self.tableWidget_2.setColumnWidth(0, 100)
        self.tableWidget_2.setColumnWidth(1, 60)
        self.tableWidget_2.setColumnWidth(2, 80)
        self.tableWidget_2.setColumnWidth(3, 60)
        self.tableWidget_2.setColumnWidth(4, 50)
        self.tableWidget_2.setColumnWidth(5, 40)
        self.tableWidget_2.setColumnWidth(6, 20)
        self.tableWidget_2.setColumnWidth(7, 20)
        self.tableWidget_2.setColumnWidth(8, 20)
        self.tableWidget_2.setColumnWidth(9, 20)
        self.tableWidget_2.setColumnWidth(10, 20)
        self.tableWidget_2.setColumnWidth(11, 20)
        self.tableWidget_2.setColumnWidth(12, 60)
        self.tableWidget_2.setColumnWidth(13, 70)
        self.tableWidget_2.setColumnWidth(14, 50)
        self.tableWidget_2.setColumnWidth(15, 60)
        self.tableWidget_2.setColumnWidth(16, 20)
        self.tableWidget_2.setColumnWidth(17, 70)
        self.tableWidget_2.setColumnWidth(18, 80)
        self.tableWidget_2.setColumnWidth(19, 80)
        self.tableWidget_2.setColumnWidth(20, 80)
        self.tableWidget_2.setColumnWidth(21, 50)
        self.tableWidget_2.setColumnWidth(22, 20)
        self.tableWidget_2.setRowCount(11)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(0, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(1, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(2, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(3, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(4, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(5, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(6, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(7, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(8, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(9, 0, item)
        item = QtWidgets.QComboBox()
        item.addItems([""])
        self.tableWidget_2.setCellWidget(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Имя и фамилия игрока")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Позиция")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Количество сыгранных игр")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Время проведенное в играх")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Количество голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Голов без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Пасы приведенные к голу")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Shorts за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Пасы приведенные к short за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сумма ожидаемых голов от удара с решающей передачей игроку")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Общее ожидание голов каждого паса, в котором участвует игрок")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Общее ожидание голов каждого паса, в котором участвует игрок без решаюшей передачи и ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов за 90 минут без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Оиждаемых пасов за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов и пасы за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов и пасы за 90 минут без пенальтий")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Ожидаемых голов каждого паса, в котором участвует игрок за 90 минут")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip(
            "Ожидаемых голов каждого паса, в котором участвует игрок за 90 минут без ключевых передач и ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Желтых карт")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Красных карт")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        self.tabWidget.addTab(self.team_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 771, 111))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setColumnWidth(0, 100)
        self.tableWidget.setColumnWidth(1, 70)
        self.tableWidget.setColumnWidth(2, 70)
        self.tableWidget.setColumnWidth(3, 70)
        self.tableWidget.setColumnWidth(4, 70)
        self.tableWidget.setColumnWidth(5, 70)
        self.tableWidget.setColumnWidth(6, 70)
        self.tableWidget.setColumnWidth(7, 70)
        self.tableWidget.setColumnWidth(8, 80)
        self.tableWidget.setColumnWidth(9, 83)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Название команды")
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Среднее владение мячом")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Всего количество ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Всего удары в ворота")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сезонное количество ударов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сезонное количество ударов в ворота")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Всего ожидаемых голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сезонных ожидаемых голов")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Сколько ударов достигло ворот")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setToolTip("Скроткр улапрв противника достигло ворот")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView.setGeometry(QtCore.QRect(0, 120, 771, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.graphWidget = pg.PlotWidget(self.graphicsView)
        self.graphWidget.setGeometry(QtCore.QRect(0, 0, 770, 265))
        self.graphWidget.setBackground('#121e29')
        blue = pg.mkPen(color=(34, 167, 240))
        red = pg.mkPen(color=(42, 187, 155))
        hour = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        temperature = [30, 32, 34, 32, 33, 31, 29, 32, 35, 45]
        temperature_2 = [50, 35, 44, 22, 38, 32, 27, 38, 32, 44]
        self.graphWidget.plot(hour, temperature, pen=blue)
        self.graphWidget.plot(hour, temperature_2, pen=red)

        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 610, 781, 151))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(190, 120, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(190, 30, 111, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setGeometry(QtCore.QRect(190, 60, 111, 16))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(320, 30, 171, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(490, 30, 16, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 30, 130, 25))
        self.pushButton_2.setObjectName("refresh")
        self.chooiseMatch = QtWidgets.QPushButton(self.groupBox)
        self.chooiseMatch.setGeometry(QtCore.QRect(620, 60, 130, 25))
        self.chooiseMatch.setObjectName("chooiseMatch")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Football Analytics"))
        self.pushButton_2.setText(_translate("MainWindow", "Применить настройки"))
        self.chooiseMatch.setText(_translate("MainWindow", "Выбор матча"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "team"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "gp"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "w"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "d"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "l"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "gf"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ga"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "gd"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "pts"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "form"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "ppg"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "last8"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "cs"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "fts"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "xg"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "npgx"))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "xga"))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "npxga"))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "npxgd"))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "ppda"))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "oppda"))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "dc"))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "odc"))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "xpts"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "player"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "position"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "appearances"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "minutes"))
        item = self.tableWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "goals"))
        item = self.tableWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "npg"))
        item = self.tableWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "a"))
        item = self.tableWidget_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "sh90"))
        item = self.tableWidget_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "kp90"))
        item = self.tableWidget_1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "xg"))
        item = self.tableWidget_1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "npxg"))
        item = self.tableWidget_1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "xa"))
        item = self.tableWidget_1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "xgchain"))
        item = self.tableWidget_1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "xgbuildup"))
        item = self.tableWidget_1.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "xg90"))
        item = self.tableWidget_1.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "npxg90"))
        item = self.tableWidget_1.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "xa90"))
        item = self.tableWidget_1.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "xg90xa90"))
        item = self.tableWidget_1.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "npxg90xa90"))
        item = self.tableWidget_1.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "xgchain90"))
        item = self.tableWidget_1.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "xgbuildup90"))
        item = self.tableWidget_1.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "yellow"))
        item = self.tableWidget_1.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "red"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.team_1), _translate("MainWindow", "Команда №1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "player"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "position"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "appearances"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "minutes"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "goals"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "npg"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "a"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "sh90"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "kp90"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "xg"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "npxg"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "xa"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "xgchain"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "xgbuildup"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "xg90"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "npxg90"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "xa90"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "xg90xa90"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "npxg90xa90"))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "xgchain90"))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "xgbuildup90"))
        item = self.tableWidget_2.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "yellow"))
        item = self.tableWidget_2.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "red"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.team_2), _translate("MainWindow", "Команда №2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "team"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "pah, %"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "shah"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "shtah"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "shs"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "shts"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "mxgah"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "sxgs"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "pshopp, %"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "pshtopp, %"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Показатели матча"))
        self.groupBox.setTitle(_translate("MainWindow", "Другие расчеты"))
        self.label_4.setText(_translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Фактический результат:"))
        self.label.setText(_translate("MainWindow", "Прогнозируемый результат:"))
        self.label_5.setText(_translate("MainWindow", "Оценка рейтинга команды №2:"))
        self.label_6.setText(_translate("MainWindow", "Оценка рейтинга команды №1:"))
        self.label_3.setText(_translate("MainWindow", "None"))
        self.label_7.setText(_translate("MainWindow", "Ожидаемый % владения мячом:"))
        self.label_8.setText(_translate("MainWindow", "0"))
